name: Rust Release

on:
  push:
    tags:
      - "v*"  # Match tags starting with "v"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build and Release Binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04] #, windows-latest]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Rust Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: install dependencies
      run: |
        sudo apt update
        sudo apt install -y cmake build-essential libjemalloc-dev libomp-dev libopenblas-dev

    - name: Build Binary
      run: cargo build --release

    - name: Upload to GitHub Releases
      uses: ncipollo/release-action@v1
      with:
        artifacts: target/release/letsearch
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref_name }}
